import { useEffect, useState } from 'react';

async function api(url, options = {}) {
  const token = localStorage.getItem('cartToken');
  const response = await fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || 'Request failed.');
  return data;
}

function Login({ onLogin }) {
  const [form, setForm] = useState({ email: 'user@example.com', password: 'user123' });
  const [error, setError] = useState('');
  async function submit(event) { event.preventDefault(); try { onLogin(await api('/api/auth/login', { method: 'POST', body: JSON.stringify(form) })); } catch (err) { setError(err.message); } }
  return <main className="login"><h1>Shopping Cart</h1><p>Sign in to continue.</p><form onSubmit={submit}><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <p className="error">{error}</p>}<button>Login</button></form><small>User: user@example.com / user123<br />Admin: admin@example.com / admin123</small></main>;
}

function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem('cartUser') || 'null'));
  const [page, setPage] = useState('shop');
  const [categories, setCategories] = useState([]);
  const [products, setProducts] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState('');
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('cartItems') || '[]'));
  const [notice, setNotice] = useState('');
  const refresh = async () => { setCategories(await api('/api/categories')); setProducts(await api('/api/products')); };
  useEffect(() => { if (session) refresh().catch(err => setNotice(err.message)); }, [session]);
  if (!session) return <Login onLogin={data => { localStorage.setItem('cartToken', data.token); localStorage.setItem('cartUser', JSON.stringify(data.user)); setSession(data.user); }} />;
  function logout() { localStorage.removeItem('cartToken'); localStorage.removeItem('cartUser'); setSession(null); }
  function addToCart(product, amount = 1) { setCart(items => { const next = items.some(item => item._id === product._id) ? items.map(item => item._id === product._id ? { ...item, quantity: Math.min(item.quantity + amount, product.stock) } : item) : [...items, { ...product, quantity: amount }]; localStorage.setItem('cartItems', JSON.stringify(next)); return next; }); setNotice(`${amount} ${product.name} added to cart.`); }
  const visibleProducts = selectedCategory ? products.filter(product => product.category?._id === selectedCategory) : products;
  return <><header><strong>Shopping Cart</strong><nav><button onClick={() => setPage('shop')}>Products</button><button onClick={() => setPage('cart')}>Cart ({cart.reduce((sum, item) => sum + item.quantity, 0)})</button>{session.role === 'admin' && <button onClick={() => setPage('admin')}>Admin</button>}<button onClick={logout}>Logout</button></nav></header><main className="container">{notice && <p className="notice">{notice}</p>}{page === 'shop' && <Shop categories={categories} products={visibleProducts} selected={selectedCategory} setSelected={setSelectedCategory} addToCart={addToCart} />}{page === 'cart' && <Cart cart={cart} setCart={setCart} />}{page === 'admin' && <Admin categories={categories} products={products} refresh={refresh} />}</main></>;
}

function Shop({ categories, products, selected, setSelected, addToCart }) { const [quantities, setQuantities] = useState({}); const top = categories.filter(category => !category.parent); return <><h1>Products</h1><div className="categories"><button className={!selected ? 'selected' : ''} onClick={() => setSelected('')}>All</button>{top.map(category => <div key={category._id}><button className={selected === category._id ? 'selected' : ''} onClick={() => setSelected(category._id)}>{category.name}</button>{categories.filter(child => String(child.parent) === category._id).map(child => <button key={child._id} className={selected === child._id ? 'selected child' : 'child'} onClick={() => setSelected(child._id)}>{child.name}</button>)}</div>)}</div><div className="products">{products.map(product => <article key={product._id}><h2>{product.name}</h2><p>{product.description}</p><p>Category: {product.category?.name}</p><strong>₹{product.price}</strong><p>Stock: {product.stock}</p><label>Quantity <input type="number" min="1" max={product.stock} value={quantities[product._id] || 1} onChange={event => setQuantities({ ...quantities, [product._id]: Math.max(1, Math.min(Number(event.target.value), product.stock)) })} /></label><button onClick={() => addToCart(product, quantities[product._id] || 1)} disabled={!product.stock}>Add to cart</button></article>)}{!products.length && <p>No products found.</p>}</div></>; }
function Cart({ cart, setCart }) { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); function remove(id) { const next = cart.filter(item => item._id !== id); setCart(next); localStorage.setItem('cartItems', JSON.stringify(next)); } return <><h1>Your cart</h1>{cart.map(item => <div className="cart-row" key={item._id}><span>{item.name} x {item.quantity}</span><strong>₹{item.price * item.quantity}</strong><button onClick={() => remove(item._id)}>Remove</button></div>)}<h2>Total: ₹{total}</h2>{!cart.length && <p>Your cart is empty.</p>}</>; }
function Admin({ categories, products, refresh }) { const [category, setCategory] = useState({ name: '', parent: '' }); const [product, setProduct] = useState({ name: '', description: '', price: '', stock: '', category: '' }); async function addCategory(event) { event.preventDefault(); await api('/api/categories', { method: 'POST', body: JSON.stringify(category) }); setCategory({ name: '', parent: '' }); refresh(); } async function addProduct(event) { event.preventDefault(); await api('/api/products', { method: 'POST', body: JSON.stringify(product) }); setProduct({ name: '', description: '', price: '', stock: '', category: '' }); refresh(); } async function remove(url) { await api(url, { method: 'DELETE' }); refresh(); } const parents = categories.filter(item => !item.parent); return <><h1>Admin panel</h1><div className="admin-grid"><form onSubmit={addCategory}><h2>Add category</h2><input placeholder="Category name" value={category.name} onChange={e => setCategory({ ...category, name: e.target.value })} required /><select value={category.parent} onChange={e => setCategory({ ...category, parent: e.target.value })}><option value="">Top-level category</option>{parents.map(item => <option key={item._id} value={item._id}>Child of {item.name}</option>)}</select><button>Add category</button></form><form onSubmit={addProduct}><h2>Add product</h2><input placeholder="Product name" value={product.name} onChange={e => setProduct({ ...product, name: e.target.value })} required /><input placeholder="Description" value={product.description} onChange={e => setProduct({ ...product, description: e.target.value })} /><input type="number" placeholder="Price" value={product.price} onChange={e => setProduct({ ...product, price: e.target.value })} required /><input type="number" placeholder="Stock" value={product.stock} onChange={e => setProduct({ ...product, stock: e.target.value })} required /><select value={product.category} onChange={e => setProduct({ ...product, category: e.target.value })} required><option value="">Select category</option>{categories.map(item => <option key={item._id} value={item._id}>{item.name}</option>)}</select><button>Add product</button></form></div><h2>Categories</h2>{categories.map(item => <div className="admin-row" key={item._id}>{item.name} {item.parent && '(child)'}<button onClick={() => remove(`/api/categories/${item._id}`)}>Delete</button></div>)}<h2>Products</h2>{products.map(item => <div className="admin-row" key={item._id}>{item.name} - ₹{item.price}<button onClick={() => remove(`/api/products/${item._id}`)}>Delete</button></div>)}</>; }

export default App;
